version: '3.8'

services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:example@db:5432/travel_matcher_development
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=travel_matcher_development
    ports:
      - "1234:5432"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8026:8025"  # Web UI port

volumes:
  postgres_data: